---
title: "clonality"
author: "Paula Restrepo"
date: "5/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = "/Users/paularstrpo/Google_Drive/Research/mssm/projects/gbm-case-study")
libs <- c('tidyverse', 'ggrepel', 'org.Hs.eg.db', 'AnnotationDbi', 'RColorBrewer', 'ggpubr', 'clonevol')
lapply(libs, library, character.only=TRUE)
rm(libs)

# set up themes for ggplotting
theme <- theme(text = element_text(size=10),
               axis.text.y = element_text(size=10, hjust = 1, face='bold'),
               axis.text.x = element_text(size=12, hjust = 1,angle=45,  face='bold'),
               axis.title = element_text(size=12, face = "bold"),
               legend.text= element_text(size=10),
               legend.title= element_text(size=11, face='bold'),
               strip.text=element_text(size=11, face='bold'))
# load inputs
load("../data/somatic_mutations.rdata")
load("../data/cnv.segments.rdata")
load("../data/cosmic.cgc.rdata")
load('../data/trueSomatic_neoantiens.rdata')
```


## set up sciclone inputs
```{r}
somatic_mutations$is_driver <- as.factor(somatic_mutations$Gene_refGene %in% cgc[cgc$Tier == 1, ]$Gene.Symbol)
somatic_mutations$combo <- paste0(somatic_mutations$sample, '_', somatic_mutations$CHROM, ':', somatic_mutations$POS)
somatic_mutations$is_neoantigen <- as.factor(somatic_mutations$combo %in% vcf_master_epitope[vcf_master_epitope$ic50 > 500, ]$combo)

vcf_table <- somatic_mutations %>%
  mutate(mutation_id=paste0(Gene_refGene, "_", CHROM, ':', POS),
         normal_cn=2,
         minor_cn=0,
         sample_gene=paste0(sample, '_',Gene_refGene)) %>%
  separate(gt_AD, c('ref_counts', "var_counts"), sep=',')
  

gene_list <- levels(as.factor(vcf_table$Gene_refGene))
  
cnv_table <- cns_table %>%
  filter(abs(log2) >= 0.25)
cnv_table <- lapply(gene_list, function(x){
  y <- cnv_table[grepl(x, cnv_table$gene, ignore.case = TRUE), ]
  if (nrow(y)!= 0) {
    y$query_gene <- x
  }
  return(y)
})
cnv_table <- do.call(rbind, cnv_table)
cnv_table <- unique(cnv_table)
cnv_table$query_gene <- as.character(cnv_table$query_gene)

cnv_table <- cnv_table %>% group_by(query_gene, sample) %>% summarise(major_cn=mean(log2)) %>%
  mutate(sample_gene=paste0(sample, '_', query_gene))
levels(cnv_table$sample) <- c('Recurrent_A', 'Recurrent_B', 'Recurrent_C', 'Primary')

pyclone_input <- vcf_table %>% left_join(cnv_table[, c('sample_gene','major_cn')], c('sample_gene'))
pyclone_input[is.na(pyclone_input$major_cn),]$major_cn  <- 0
pyclone_input$major_cn <- 2^pyclone_input$major_cn

```

```{r eval=FALSE}
for (s in levels(cnv_table$sample)){
  pyclone_input %>% filter(sample == s) %>%
    dplyr::select(mutation_id, ref_counts, var_counts, normal_cn, minor_cn, major_cn, Gene_refGene, ExonicFunc_refGene,Func_refGene, is_driver, is_neoantigen, variant, sample) %>%
    write_tsv(path = paste0('../raw_data/pcylone/', s, '.tsv') )
}
```

```{r}
pyclone_results <- read_tsv('../raw_data/pcylone/pyclone_results_old_style.tsv')
colnames(pyclone_results) <- c('mutation_id', paste0(c('Recurrent_A', 'Recurrent_B', 'Recurrent_C', 'Primary'), '.vaf'), paste0(c('Recurrent_A', 'Recurrent_B', 'Recurrent_C', 'Primary'), '.ccf'), 'cluster_id' )
                               
tmp <- pyclone_input %>% dplyr::select(mutation_id, Gene_refGene, is_driver, is_neoantigen)
pyclone_results <- pyclone_results %>%
  inner_join(tmp, by=c('mutation_id')) %>%
  mutate(cluster=cluster_id)

rm(tmp)
```

```{r}
# create adjacency matrix using mutation overlaps

##function set up
count <- function(x,y){ f<- table(rbind(x,y)); sum(f[f>1])/sum(f) }

hm.palette <- colorRampPalette(rev(brewer.pal(9, 'YlGnBu')), space='Lab')
hm.theme <-  theme(legend.position='bottom',
                legend.justification='left',
                panel.background = element_rect(fill="white", color='black'),
                panel.grid.major = element_line(color='black', size=0.1),
                panel.grid.minor=element_line(color='black', size=0.1),
                axis.text.x = element_text(angle = 45, hjust = 1),
                text = element_text(size=25))


# compute overlaps and save adjacency for later
vcf_filtered_df_OL <- somatic_mutations
vcf_filtered_df_OL$sample <- as.factor(as.character(vcf_filtered_df_OL$sample))
mutation_overlap <- NULL

for (sample in levels(vcf_filtered_df_OL$sample)){
    idx <- vcf_filtered_df_OL$sample == sample
    mutation_overlap[[sample]] <- unique(as.matrix(factor(vcf_filtered_df_OL[idx,]$variant)))
}

m <- sapply(mutation_overlap, function(x) sapply(mutation_overlap, function(y) count(x,y)))
rownames(m) <-levels(vcf_filtered_df_OL$sample)
colnames(m) <- levels(vcf_filtered_df_OL$sample)


mutation_overlap <- reshape2::melt(m)
colnames(mutation_overlap) <- c('sample1', 'sample2', 'overlap')

# moverlap
mut_overlap <- ggplot(data= mutation_overlap) + aes(x = sample1, y = sample2) +
    geom_tile(aes(fill = round(overlap * 100, 2))) +
    geom_label(data = mutation_overlap, aes(label = round(overlap * 100, 2)), size=5) +
    labs(x='', y='') +
    scale_fill_gradientn(colours = hm.palette(100), name='% Overlap', limits= c(0,100)) +
    hm.theme +
    ggtitle("Mutation Overlap")

rm(m)

```

```{r}
 read_tsv('../raw_data/pcylone/pyclone_results_loci.tsv') %>% group_by(cluster_id) %>% summarise(max=max(variant_allele_frequency))
```

cluster 6 is the founding cluster.

```{r}
vaf.col.names =paste0(c('Recurrent_A', 'Recurrent_B', 'Recurrent_C', 'Primary'), '.vaf')
ccf.col.names=paste0(c('Recurrent_A', 'Recurrent_B', 'Recurrent_C', 'Primary'), '.ccf')
sample.names = c('Recurrent_A', 'Recurrent_B', 'Recurrent_C', 'Primary')
sample.groups = c('r', 'r', 'r', 'p')

pyclone_results[, vaf.col.names] <- lapply(pyclone_results[, vaf.col.names], function(x){x * 100})
pyclone_results[, ccf.col.names] <- lapply(pyclone_results[, ccf.col.names], function(x){x * 100})
pyclone_results <- unique(pyclone_results)
```


```{r}

y = infer.clonal.models(variants = pyclone_results, 
                        cluster.col.name =  "cluster", 
                        ccf.col.names = ccf.col.names,
                        cancer.initiation.model='polyclonal', 
                        subclonal.test = 'bootstrap', 
                        subclonal.test.model = 'non-parametric',
                        num.boots = 8000,
                        sample.names=sample.names,
                        founding.cluster =6,
                        cluster.center = 'mean',
                        clone.colors = brewer.pal(n=6, name = 'Spectral'),
                        min.cluster.vaf = 0.05,
                        sum.p = 0.001,
                        alpha=0.05,
                        random.seed = 123,
                        seeding.aware.tree.pruning = TRUE)

clonal_models = convert.consensus.tree.clone.to.branch(y, branch.scale = 'sqrt')

```


```{r}
# plot trees only
pdf('../figures/clonevol_trees.pdf', width =8, height = 11)
plot.all.trees.clone.as.branch(clonal_models, branch.width =0.1,
                               node.size = 2, node.label.size = 1)
dev.off()
```



```{r}
save(somatic_mutations, file='../data/somatic_mutations.rdata')
```

